[workspace]
resolver = "2"
members = [
    "rx-core",
    "rx-db",
    "rx-db-derive",
    "rx-net",
    "rx-rest",
    "rx-fst",
    #"rx-web",
    #"binder",
    #"bin-parser",
    #"netplan-cfg",
]
