[package]
name = "rx-db"
version = "0.1.0"
authors = ["dayn9t <dayn9t@gmail.com>"]
edition = "2021"

[dependencies]
rx-core = { path = "../rx-core" }
rx-db-derive = { path = "../rx-db-derive" }

serde = { version = "*", features = ["derive"] }
serde_json = "*"

redis = "*"

anyhow = "*"
thiserror = "*"
